remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: eurocat2k's thoughts
description: As an ATC system administrator and system programmer, I faced with lot of challenges in the past decades. Here I present many of them in system programmer's context.

