remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
<<<<<<< HEAD
title: Thoughts
description: A short description of your site's purpose
=======
>>>>>>> 69c2dbf5a1b81b0d42ad428d51775376a04b83ea
